### ISSUE TITLE
PCB Files

### ISSUE THREAD

**Issue by denonbw** [camnewnham/motorboard#1]
The description says something about PCB. Are there PCB files for this project?

**Comment by camnewnham** [comment]
Here you go - I ended up using a wemos d1 mini and stepstick style tmc2209. So the PCB was mostly a power regulation board that connected the two together: https://oshwlab.com/camnewnham/curtain-breakout-board

I was working on a board to fit in the footprint of a NEMA17 motor and allow WiFi control, but I never had it manufactured: https://oshwlab.com/project/publish/4aeac50195554ce1b033e3e02b8c43e1
